BACKGROUND_COLOR_DEFAULT = "#ffffff"
LINE_COLOR_DEFAULT = "#000000"
FONT_STANDARD_SIZE = 16
FONT_BIG_SIZE = 20
FONT_TYPE = "Times"
BIG_ELEM_MINIMUM_SIZE = 50
GRAPH_MINIMUM_WIDTH = 600
FIELD_LIM = (-30, 30)
