name: Check
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                pip install ruff
                pip install pyqtgraph
            - name: Lint
              run:  
                ruff --output-format=github .
            - name: Test
              run: |
                cd ./lab_01_34/unit_tests
                python3 -m unittest discover -p 'test_*.py'
